// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/compression/compression.d.ts
// Type definitions for compression
// Project: https://github.com/expressjs/compression
// Definitions by: Santi Albo <https://github.com/santialbo/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


declare module "compression" {
    import express = require('express');

    namespace e {
        interface CompressionOptions  {
            threshold?: number;
            filter?: Function;
        }
    }

    function e(options?: e.CompressionOptions): express.RequestHandler;
    export = e;
}